project:
  type: website
website:
  title: "CAAD Futures 2025"
  favicon: "Stamp_CAADFutures2025_OUTLN.png"
  # back-to-top-navigation: true
  page-footer: 
    background: black
    left: 
      <div>© 2025, Hong Kong University, All rights reserved.</div>
    center: |
      <div>
      <img src="foabanner_inverted.png" alt="faculty of arch" style="height: 30px; margin-right: 10px; margin-top: 10px">
      </div>
    right: |
      <a href="https://sites.google.com/unicamp.br/caadfutures/" target="_blank">
      <img src="caadfutures_new logo.png" alt="caadfutures" style="height: 30px; margin-right: 10px;">
      </a>
  search: 
    location: sidebar
  sidebar:
    search: false
    
  navbar:
    # logo: "Stamp_CAADFutures2025_OUTLN.png"
    right:
      - text: "Home"
        href: index.qmd
      - text: "Programme"
        menu:
          # - text: "Regular Papers"
          #   href: regular.qmd
          # - text: "Catalytic Interfaces"
          #   href: props.qmd
          # - text: "Presentation Format"
          #   href: present.qmd
          - text: "Technical Programme"
            href: conference_papers.qmd
          - text: "Conference Schedule"
            href: schedule.qmd
          - text: "Catalytic Interfaces Activities"
            href: CI_acts.qmd
      - text: "Instructions"
        menu:
          - text: "Paper: Regular Papers"
            href: regular.qmd
          - text: "Paper: Catalytic Interfaces"
            href: props.qmd
          - text: "Presentation: All Streams"
            href: present.qmd
          - text: "Setup: Catalytic Interfaces"
            href: CI_setup.qmd
          # - text: "Technical Programme"
          #   href: conference_papers.qmd
          # - text: "Conference Schedule"
          #   href: schedule.qmd
      - text: "Keynotes"
        href: keynote.qmd
      - text: "Tickets"
        menu:
          - text: "Public Keynote"
            href: keynotes/Shigeru.qmd
          - text: "General Ticketing"
            href: ticketing.qmd
          - text: "Side Events"
            href: events_lineup.qmd
      - text: "About"
        menu:
          - text: "Travel Info"
            href: travel.qmd
          - text: "Committee"
            href: committee.qmd
          - text: "Ambition"
            href: ambition.qmd

format:
  html:
    page-layout: full
    theme: lux
    css: styles.css
    toc: true