---
title: "Ambition of CAAD Futures 2025"
format:
  html:
    theme: quartz
    toc: true
---


### CALL FOR PAPERS AND CATALYTIC INTERFACE PROPOSALS

We are pleased to announce that CAAD Futures 2025 will be held at the University of Hong Kong during the first week of July 2025. 
 
The theme of CAAD Futures 2025 is 'Catalytic Interfaces’. This reflects our goals (i) to catalyse collaborative and interdisciplinary research initiatives around emergent computer-aided architectural design (CAAD) research priorities, and (ii) to provide a platform for local, regional, and international researchers in the field of CAAD to interface and collaborate. 
 
To achieve this, we have designed a dynamic <mark>two-pronged programme</mark>. Our conference features <mark>Regular Paper Presentations</mark>. on emergent interfacing CAAD research. Additionally, a dedicated series of team-based <mark>'Catalytic Interface' programming</mark> will provide infrastructure, both physical and digital, along with focused time and attention for fostering collaboration on new research priorities both during and prior to the conference. 
 
You are receiving this email because we recognise you as a research catalyser in the field of CAAD research. We invite you to participate in our conference through one or both of the two programmes mentioned above: 
 

<h4 style="text-align: center;">Team Participation in 'Catalytic Interfaces'</h4>
 
We invite researchers to take advantage of the special ‘Catalytic Interface’ programming.  Interested researchers are asked to form teams around a core expertise, and develop ideas for interdisciplinary research that interface with one or multiple CAAD topic areas.  Dedicated ‘Catalytic Interface’ programming and infrastructure both before and during the conference will offer a platform for selected teams to collaborate with like-minded teams with relevant expertise, catalysing initial discussions as well as the prototyping of ideas during the conference.   
 
Specifically, the process begins with team formation and submission of Initial Statement of Interest by `16 September 2024`.   

<mark>We are still actively working to set up the submission system. Please revisit in early September for updates, and we appreciate your enthusiasm and patience in the meantime.</mark>
 
Statements are peer-reviewed and promising statements and teams are then selected.  Next, a series of online catalyser events are held to foster productive team pairs/groupings around emergent CAAD priorities synthesising their interests.  Team pairs/groupings will then submit Proposals that set the stage for their collaboration during the three-day conference to prototype their ideas. Ultimately, these efforts will culminate in the publication of peer-reviewed proposals through the conference’s companion publication, as well as public presentations at the end of the conference.  See [A1](conference_theme.qmd) for additional details on the special programming and [A3](20240809_Timeline_WIP.pdf) for a tentative timeline of both programme and the submission process. 
 
Submissions shall include the following items: 

a. A succinct and descriptive title;  
b. List of team members with a 100-word biography for each member; 
c. The CAAD area(s) related to the team’s core expertise and interests; and  
d. Identified CAAD areas where the team seeks collaboration via ‘Catalytic Interfaces’; 
e. A Statement of Interest of no longer than 1000 words that clearly describes a research question or thesis that the team wishes to develop through ‘Catalytic Interfaces’, synthesising CAAD areas in c and d, and outlining the potential benefits and anticipated impact of this synthesis on architecture. 
 
A tentative <mark>Expert Invitation Award</mark> will also be offered to outstanding proposals to sponsor the travel of team members or their invitees, aiming to enhance the potential for impactful collaboration and output.  
 

<h4 style="text-align: center;">Regular Paper Submission </h4>

 
We invite researchers to submit abstracts by `16 September 2024`.  

<mark>We are still actively working to set up the submission system. Please revisit in early September for updates, and we appreciate your enthusiasm and patience in the meantime.</mark>
 
Abstracts should be of no longer than 250 words.  The submission process includes initial abstract submission and acceptance upon peer review, followed additionally by one to two peer review rounds.  Abstract decisions will be announced by 28 October 2024; paper decisions for the two revision rounds will be announced by 17 February 2025 and 7 April 2025, respectively.  Please note that all dates are tentative.   
 
High-quality submissions will be selected for publication by the end of the first review round either as (A) long papers in a Springer publication or as (B) short papers in a companion conference publication. The selection for these categories will be based on both quality as well as the curation of the conference programme. We especially welcome research papers pioneering novel CAAD paradigm interfacing multiple CAAD technologies.    See [A2](topics.qmd) for a list of potential paper topics and [A3](20240809_Timeline_WIP.pdf) for a tentative timeline of the submission process.  
 
 
Thank you in advance for your participation, and we very much look forward to welcoming you in Hong Kong next year! 


Yours sincerely, CAADFutures 2025 Organising Committee\
Prof. Kristof Crolla\
Prof. Kam-Ming Mark Tam\
Prof. Hongshan Guo\
Dr. Garvin Goepel\
Mr. Haotian Zhang

